// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7dhU8vpFqRat-RNZrkzlr6rFHsRUN-xU',
    appId: '1:261833109923:web:fa44c92799e4fea845ea16',
    messagingSenderId: '261833109923',
    projectId: 'flickfinder-111b1',
    authDomain: 'flickfinder-111b1.firebaseapp.com',
    storageBucket: 'flickfinder-111b1.firebasestorage.app',
    measurementId: 'G-8Z131941CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB907GMMnoUHZaezrrFwnwROKkZW1ie1kQ',
    appId: '1:261833109923:android:eb80178f2525478b45ea16',
    messagingSenderId: '261833109923',
    projectId: 'flickfinder-111b1',
    storageBucket: 'flickfinder-111b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQgLfrLUmZi9RI7QJVy7uhmLiyzwHkmA',
    appId: '1:261833109923:ios:0be0ebc464073ac645ea16',
    messagingSenderId: '261833109923',
    projectId: 'flickfinder-111b1',
    storageBucket: 'flickfinder-111b1.firebasestorage.app',
    iosBundleId: 'com.example.flickFindr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEQgLfrLUmZi9RI7QJVy7uhmLiyzwHkmA',
    appId: '1:261833109923:ios:0be0ebc464073ac645ea16',
    messagingSenderId: '261833109923',
    projectId: 'flickfinder-111b1',
    storageBucket: 'flickfinder-111b1.firebasestorage.app',
    iosBundleId: 'com.example.flickFindr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7dhU8vpFqRat-RNZrkzlr6rFHsRUN-xU',
    appId: '1:261833109923:web:8f33de6a5eabfcd045ea16',
    messagingSenderId: '261833109923',
    projectId: 'flickfinder-111b1',
    authDomain: 'flickfinder-111b1.firebaseapp.com',
    storageBucket: 'flickfinder-111b1.firebasestorage.app',
    measurementId: 'G-DX6DZS4PVP',
  );
}
